Fixed python3 path - v3.2.5

diff --git a/cleanupssh b/cleanupssh
--- a/cleanupssh
+++ b/cleanupssh
@@ -28,7 +28,7 @@
 
 # parse args
 #
-export VERSION="3.2.4"
+export VERSION="3.2.5"
 export USAGE="usage: $0 [-n] [-v] [-f] [-i] [-t] [-s] [-S] [-c user[:group]] [-V] [-h] dir
 
     -n		Do nothing (def: do)
@@ -180,7 +180,6 @@ if [[ -z $CAP_S_FLAG ]]; then
 	fi
     else
 	if [[ -n "$V_FLAG" ]]; then
-	    echo
 	    echo "# will use known_hosts_cleanup from: $KNOWN_HOSTS_CLEANUP"
 	fi
     fi
@@ -190,9 +189,47 @@ else
     fi
 fi
 
+# look for python3
+#
+export PYTHON3 PYTHON3_VERSION
+if [[ -x /usr/bin/python3 ]]; then
+    PYTHON3="/usr/bin/python3"
+elif [[ -x /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 ]]; then
+    PYTHON3="/Library/Frameworks/Python.framework/Versions/3.7/bin/python3"
+elif [[ -x /bin/python3 ]]; then
+    PYTHON3="/bin/python3"
+elif [[ -x /usr/local/bin/python3 ]]; then
+    PYTHON3="/usr/local/bin/python3"
+elif [[ -x /usr/global/bin/python3 ]]; then
+    PYTHON3="/usr/global/bin/python3"
+else
+    PYTHON3=$(which python3 2>/dev/null)
+fi
+if [[ -z $PYTHON3 ]]; then
+    echo "$0: Warning: cannot find python3 executable" 1>&2
+    echo "$0: Warning: forcing -S to disable known_hosts_cleanup" 1>&2
+    CAP_S_FLAG="-S"
+else
+    if [[ -n "$V_FLAG" ]]; then
+	echo
+	echo "# testing version of python3 using: $PYTHON3 -V 2>/dev/null"
+    fi
+    PYTHON3_VERSION=$("$PYTHON3" -V 2>/dev/null)
+    status="$?"
+    if [[ $status -ne 0 || -z "$PYTHON3_VERSION" ]]; then
+	echo "$0: Warning: cannot determine version of python3: $PYTHON3" 1>&2
+	echo "$0: Warning: python3 -V, error code: $status" 1>&2
+	echo "$0: Warning: forcing -S to disable known_hosts_cleanup" 1>&2
+	CAP_S_FLAG="-S"
+    elif [[ -n "$V_FLAG" ]]; then
+	echo "# python3 version: $PYTHON3_VERSION"
+    fi
+fi
+
 # form missing critical directories
 #
 if [[ -n "$V_FLAG" ]]; then
+    echo
     echo '# Processing critical directories'
 fi
 if [[ ! -d sock ]]; then
@@ -514,14 +551,14 @@ if [[ -z $CAP_S_FLAG ]]; then
 	fi
     else
 	if [[ -n "$V_FLAG" ]]; then
-	    echo "python3 $KNOWN_HOSTS_CLEANUP -v known_hosts > $SORTED_TMP"
+	    echo "$PYTHON3 $KNOWN_HOSTS_CLEANUP -v known_hosts > $SORTED_TMP"
 	fi
 	if [[ -z "$N_FLAG" ]]; then
 	    if [[ -n "$V_FLAG" ]]; then
-		python3 "$KNOWN_HOSTS_CLEANUP" -v known_hosts > "$SORTED_TMP"
+		"$PYTHON3" "$KNOWN_HOSTS_CLEANUP" -v known_hosts > "$SORTED_TMP"
 		status="$?"
 	    else
-		python3 "$KNOWN_HOSTS_CLEANUP" known_hosts > "$SORTED_TMP"
+		"$PYTHON3" "$KNOWN_HOSTS_CLEANUP" known_hosts > "$SORTED_TMP"
 		status="$?"
 	    fi
 	else
@@ -529,11 +566,11 @@ if [[ -z $CAP_S_FLAG ]]; then
 	fi
 	if [[ $status -ne 0 ]]; then
 	    if [[ -z "$F_FLAG" ]]; then
-		echo "$0: FATAL: python3 $KNOWN_HOSTS_CLEANUP -v known_hosts > $SORTED_TMP, error code: $status" 1>&2
+		echo "$0: FATAL: $PYTHON3 $KNOWN_HOSTS_CLEANUP -v known_hosts > $SORTED_TMP, error code: $status" 1>&2
 		echo "$0: FATAL: exit 29" 1>&2
 		exit 29
 	    else
-		echo "$0: Warning: python3 $KNOWN_HOSTS_CLEANUP -v known_hosts > $SORTED_TMP, error code: $status" 1>&2
+		echo "$0: Warning: $PYTHON3 $KNOWN_HOSTS_CLEANUP -v known_hosts > $SORTED_TMP, error code: $status" 1>&2
 	    fi
 	fi
     fi
