fixes from dot

diff --git a/cleanupssh b/cleanupssh
--- a/cleanupssh
+++ b/cleanupssh
@@ -2,7 +2,7 @@
 #
 # cleanupssh - cleanup a .ssh directory
 #
-# Copyright (c) 2015 by Landon Curt Noll.  All Rights Reserved.
+# Copyright (c) 2015,2016 by Landon Curt Noll.  All Rights Reserved.
 #
 # Permission to use, copy, modify, and distribute this software and
 # its documentation for any purpose and without fee is hereby granted,
@@ -158,6 +158,32 @@ if [[ -z "$N_FLAG" && ! -w OLD ]]; then
     echo "$0: FATAL: directory not writable: OLD" 1>&2
     exit 15
 fi
+if [[ ! -d from ]]; then
+    if [[ -z "$N_FLAG" ]]; then
+	mkdir $V_FLAG from
+	status="$?"
+	if [[ ! -d from ]]; then
+	    echo "$0: FATAL cannot mkdir from, error code: $status" 1>&2
+	    exit 16
+	fi
+    elif [[ -n "$V_FLAG" ]]; then
+	echo mkdir $V_FLAG from
+    fi
+fi
+if [[ -z "$N_FLAG" ]]; then
+    chmod $V_FLAG 0700 from
+    status="$?"
+    if [[ $status -ne 0 ]]; then
+	echo "$0: FATAL: chmod 0700 from, error code: $status" 1>&2
+	exit 17
+    fi
+elif [[ -n "$V_FLAG" ]]; then
+    echo chmod $V_FLAG 0700 from
+fi
+if [[ -z "$N_FLAG" && ! -w from ]]; then
+    echo "$0: FATAL: directory not writable: from" 1>&2
+    exit 18
+fi
 
 # set file permissions
 #
@@ -166,16 +192,31 @@ if [[ -n "$V_FLAG" ]]; then
 fi
 if [[ -z "$N_FLAG" ]]; then
     chmod $V_FLAG 0700 .
-    find . -mindepth 1 -maxdepth 1 -type f -name 'authorized_keys*' -print0 |
-      xargs $XARGS_V -0 chmod $V_FLAG 0400
-    find . -mindepth 1 -maxdepth 1 -type f -name 'config*' -print0 |
-      xargs $XARGS_V -0 chmod $V_FLAG 0400
-    find . -mindepth 1 -maxdepth 1 -type f ! -name 'id_rsa.pub*' -name 'id_rsa*' -print0 |
-      xargs $XARGS_V -0 chmod $V_FLAG 0400
-    find . -mindepth 1 -maxdepth 1 -type f -name 'id_rsa.pub*' -print0 |
-      xargs $XARGS_V -0 chmod $V_FLAG 0444
-    find . -mindepth 1 -maxdepth 1 -type f -name 'known_hosts*' -print0 |
-      xargs $XARGS_V -0 chmod $V_FLAG 0664
+    SET=$(find . -mindepth 1 -maxdepth 1 -type f -name 'authorized_keys*' -print)
+    if [[ -n $SET ]]; then
+	find . -mindepth 1 -maxdepth 1 -type f -name 'authorized_keys*' -print0 |
+	  xargs $XARGS_V -0 chmod $V_FLAG 0400
+    fi
+    SET=$(find . -mindepth 1 -maxdepth 1 -type f -name 'config*' -print)
+    if [[ -n $SET ]]; then
+	find . -mindepth 1 -maxdepth 1 -type f -name 'config*' -print0 |
+	  xargs $XARGS_V -0 chmod $V_FLAG 0400
+    fi
+    SET=$(find . -mindepth 1 -maxdepth 1 -type f ! -name 'id_rsa.pub*' -name 'id_rsa*' -print)
+    if [[ -n $SET ]]; then
+	find . -mindepth 1 -maxdepth 1 -type f ! -name 'id_rsa.pub*' -name 'id_rsa*' -print0 |
+	  xargs $XARGS_V -0 chmod $V_FLAG 0400
+    fi
+    SET=$(find . -mindepth 1 -maxdepth 1 -type f -name 'id_rsa.pub*' -print)
+    if [[ -n $SET ]]; then
+	find . -mindepth 1 -maxdepth 1 -type f -name 'id_rsa.pub*' -print0 |
+	  xargs $XARGS_V -0 chmod $V_FLAG 0444
+    fi
+    SET=$(find . -mindepth 1 -maxdepth 1 -type f -name 'known_hosts*' -print)
+    if [[ -n $SET ]]; then
+	find . -mindepth 1 -maxdepth 1 -type f -name 'known_hosts*' -print0 |
+	  xargs $XARGS_V -0 chmod $V_FLAG 0664
+    fi
 elif [[ -n "$V_FLAG" ]]; then
     echo chmod $V_FLAG 0700 .
     find . -mindepth 1 -maxdepth 1 -type f -name 'authorized_keys*' -print0 |
@@ -192,9 +233,7 @@ fi
 
 # move all but the last dated element of certain files into OLD
 #
-for file in authorized_keys config.sonic.any config.arcetri.non-root \
-  config.arcetri.root config.arcetri.chongo config.isthe.any config \
-  id_rsa id_rsa.pub known_hosts; do
+for file in authorized_keys config id_rsa id_rsa.pub known_hosts; do
     if [[ -n "$V_FLAG" ]]; then
 	echo "# processing fileset: $file"
     fi
@@ -213,6 +252,21 @@ for file in authorized_keys config.sonic.any config.arcetri.non-root \
     fi
     done
 done
+
+# old top level from- and no-
+#
+find . -mindepth 1 -maxdepth 1 -type f \( -name 'from-*' -o -name 'no-*' \) -print |
+    while read i; do
+    if [[ -z "$N_FLAG" ]]; then
+	mv $V_FLAG "$i" OLD
+	status="$?"
+	if [[ $status -ne 0 ]]; then
+	    echo "$0: Warning: mv $V_FLAG $i OLD, error code: $status" 1>&2
+	fi
+    elif [[ -n "$V_FLAG" ]]; then
+	echo mv $V_FLAG "$i" OLD
+    fi
+    done
 
 # All Done!!! - Jessica Noll, Age 2
 #
