Improved handling missing critical files

diff --git a/cleanupssh b/cleanupssh
--- a/cleanupssh
+++ b/cleanupssh
@@ -32,7 +32,7 @@ export USAGE="usage: $0 [-n] [-v] dir
 
     -n		do nothing (def: do)
     -v		verbose mode (def: quiet)
-    -f		force cleanup if authorized_keys is missing
+    -f		force cleanup if authorized_keys, id_rsa or id_rsa.pub is missing
     -h		print this message and exit
 
     dir		.ssh directory to clean up"
@@ -222,21 +222,43 @@ if [[ -z "$N_FLAG" ]]; then
     fi
 elif [[ -n "$V_FLAG" ]]; then
     echo chmod $V_FLAG 0700 .
-    find . -mindepth 1 -maxdepth 1 -type f -name 'authorized_keys*' -print0 |
-      xargs -0 echo chmod $V_FLAG 0400
-    find . -mindepth 1 -maxdepth 1 -type f -name 'config*' -print0 |
-      xargs -0 echo chmod $V_FLAG 0400
-    find . -mindepth 1 -maxdepth 1 -type f ! -name 'id_rsa.pub*' -name 'id_rsa*' -print0 |
-      xargs -0 echo chmod $V_FLAG 0400
-    find . -mindepth 1 -maxdepth 1 -type f -name 'id_rsa.pub*' -print0 |
-      xargs -0 echo chmod $V_FLAG 0444
-    find . -mindepth 1 -maxdepth 1 -type f -name 'known_hosts*' -print0 |
-      xargs -0 echo chmod $V_FLAG 0664
+    SET=$(find . -mindepth 1 -maxdepth 1 -type f -name 'authorized_keys*' -print)
+    if [[ -n $SET ]]; then
+	find . -mindepth 1 -maxdepth 1 -type f -name 'authorized_keys*' -print0 |
+	  xargs -0 echo chmod $V_FLAG 0400
+    fi
+    SET=$(find . -mindepth 1 -maxdepth 1 -type f -name 'config*' -print)
+    if [[ -n $SET ]]; then
+	find . -mindepth 1 -maxdepth 1 -type f -name 'config*' -print0 |
+	  xargs -0 echo chmod $V_FLAG 0400
+    fi
+    SET=$(find . -mindepth 1 -maxdepth 1 -type f ! -name 'id_rsa.pub*' -name 'id_rsa*' -print)
+    if [[ -n $SET ]]; then
+	find . -mindepth 1 -maxdepth 1 -type f ! -name 'id_rsa.pub*' -name 'id_rsa*' -print0 |
+	  xargs -0 echo chmod $V_FLAG 0400
+    fi
+    SET=$(find . -mindepth 1 -maxdepth 1 -type f -name 'id_rsa.pub*' -print)
+    if [[ -n $SET ]]; then
+	find . -mindepth 1 -maxdepth 1 -type f -name 'id_rsa.pub*' -print0 |
+	  xargs -0 echo chmod $V_FLAG 0444
+    fi
+    SET=$(find . -mindepth 1 -maxdepth 1 -type f -name 'known_hosts*' -print)
+    if [[ -n $SET ]]; then
+	find . -mindepth 1 -maxdepth 1 -type f -name 'known_hosts*' -print0 |
+	  xargs -0 echo chmod $V_FLAG 0664
+    fi
 fi
 
 # Insure that critical files have a dated copy
 #
 for file in authorized_keys config id_rsa id_rsa.pub known_hosts; do
+
+    # catch the case of a missing critical file
+    #
+    if [[ ! -f "$file" ]]; then
+	echo "$0: Warning: $dir is missing $file" 1>&2
+	continue
+    fi
 
     # determine the dated filename
     #
@@ -278,22 +300,21 @@ for file in authorized_keys config id_rsa id_rsa.pub known_hosts; do
       -name "$file"'.[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]' -o \
       -name "$file"'.[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][a-z]' \) |
       sort -r | awk 'NR != 1 {print $0;}' | while read i; do
-    if [[ -z "$N_FLAG" ]]; then
-	mv $V_FLAG "$i" OLD
-	status="$?"
-	if [[ $status -ne 0 ]]; then
-	    echo "$0: Warning: mv $V_FLAG $i OLD, error code: $status" 1>&2
+	if [[ -z "$N_FLAG" ]]; then
+	    mv $V_FLAG "$i" OLD
+	    status="$?"
+	    if [[ $status -ne 0 ]]; then
+		echo "$0: Warning: mv $V_FLAG $i OLD, error code: $status" 1>&2
+	    fi
+	elif [[ -n "$V_FLAG" ]]; then
+	    echo mv $V_FLAG "$i" OLD
 	fi
-    elif [[ -n "$V_FLAG" ]]; then
-	echo mv $V_FLAG "$i" OLD
-    fi
     done
 done
 
 # old top level from- and no-
 #
-find . -mindepth 1 -maxdepth 1 -type f \( -name 'from-*' -o -name 'no-*' \) -print |
-    while read i; do
+find . -mindepth 1 -maxdepth 1 -type f \( -name 'from-*' -o -name 'no-*' \) -print | while read i; do
     if [[ -z "$N_FLAG" ]]; then
 	mv $V_FLAG "$i" OLD
 	status="$?"
@@ -303,7 +324,7 @@ find . -mindepth 1 -maxdepth 1 -type f \( -name 'from-*' -o -name 'no-*' \) -pri
     elif [[ -n "$V_FLAG" ]]; then
 	echo mv $V_FLAG "$i" OLD
     fi
-    done
+done
 
 # clean up .nfs files in sock that are older than 1 day
 #
