Always created dated files for critical files

diff --git a/cleanupssh b/cleanupssh
--- a/cleanupssh
+++ b/cleanupssh
@@ -231,6 +231,35 @@ elif [[ -n "$V_FLAG" ]]; then
       xargs -0 echo chmod $V_FLAG 0664
 fi
 
+# ensure that critical files have a dated copy
+#
+for file in authorized_keys config id_rsa id_rsa.pub known_hosts; do
+
+    # determine the dated filename
+    #
+    date_file="$file."$(ls --full-time "$file" | awk '{print $6, $7;}' | sed -e 's/\.[0-9]*$//' -e 's/[:-]//g' -e 's/ /./')
+    if [[ -z $date_file ]]; then
+	echo "$0: FATAL: cannot determinte date for file: $file" 1>&2
+	exit 19
+    fi
+
+    # unless the timestamped file is a copy of the original, form it
+    #
+    if ! cmp -s "$file" "$date_file"; then
+	if [[ -n "$V_FLAG" ]]; then
+	    echo "cp -p $file $date_file"
+	fi
+	if [[ -z "$N_FLAG" ]]; then
+	    cp -p "$file" "$date_file"
+	    status="$?"
+	    if [[ $status -ne 0 ]]; then
+		echo "$0: FATAL: cp -p $file $date_file, error code: $status" 1>&2
+		exit 20
+	    fi
+	fi
+    fi
+done
+
 # move all but the last dated element of certain files into OLD
 #
 for file in authorized_keys config id_rsa id_rsa.pub known_hosts; do
@@ -239,6 +268,7 @@ for file in authorized_keys config id_rsa id_rsa.pub known_hosts; do
     fi
     find . -mindepth 1 -maxdepth 1 -type f \( \
       -name "$file"'.[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' -o \
+      -name "$file"'.[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]' -o \
       -name "$file"'.[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][a-z]' \) |
       sort -r | awk 'NR != 1 {print $0;}' | while read i; do
     if [[ -z "$N_FLAG" ]]; then
