Improve python3 use, v3.2.3

diff --git a/cleanupssh b/cleanupssh
--- a/cleanupssh
+++ b/cleanupssh
@@ -28,7 +28,7 @@
 
 # parse args
 #
-export VERSION="3.2.2"
+export VERSION="3.2.3"
 export USAGE="usage: $0 [-n] [-v] [-f] [-i] [-s] [-S] [-c user[:group]] [-V] [-h] dir
 
     -n		Do nothing (def: do)
@@ -442,21 +442,21 @@ if [[ -z $CAP_S_FLAG ]]; then
 	fi
     else
 	if [[ -n "$V_FLAG" ]]; then
-	    echo "$KNOWN_HOSTS_CLEANUP -v known_hosts > $SORTED_TMP"
+	    echo "python3 $KNOWN_HOSTS_CLEANUP -v known_hosts > $SORTED_TMP"
 	fi
 	if [[ -z "$N_FLAG" ]]; then
 	    if [[ -n "$V_FLAG" ]]; then
-		"$KNOWN_HOSTS_CLEANUP" -v known_hosts > "$SORTED_TMP"
+		python3 "$KNOWN_HOSTS_CLEANUP" -v known_hosts > "$SORTED_TMP"
 		status="$?"
 	    else
-		"$KNOWN_HOSTS_CLEANUP" known_hosts > "$SORTED_TMP"
+		python3 "$KNOWN_HOSTS_CLEANUP" known_hosts > "$SORTED_TMP"
 		status="$?"
 	    fi
 	else
 	    status=0
 	fi
 	if [[ $status -ne 0 ]]; then
-	    echo "$0: FATAL: $KNOWN_HOSTS_CLEANUP -v known_hosts > $SORTED_TMP, error code: $status" 1>&2
+	    echo "$0: FATAL: python3 $KNOWN_HOSTS_CLEANUP -v known_hosts > $SORTED_TMP, error code: $status" 1>&2
 	    echo "$0: FATAL: exit 29" 1>&2
 	    exit 29
 	fi
