process id_ed25519 keys, python nit

diff --git a/cleanupssh b/cleanupssh
--- a/cleanupssh
+++ b/cleanupssh
@@ -2,7 +2,7 @@
 #
 # cleanupssh - cleanup a .ssh directory
 #
-# Copyright (c) 2015-2020,2023-2025 by Landon Curt Noll.  All Rights Reserved.
+# Copyright (c) 2015-2020,2023-2026 by Landon Curt Noll.  All Rights Reserved.
 #
 # Permission to use, copy, modify, and distribute this software and
 # its documentation for any purpose and without fee is hereby granted,
@@ -32,7 +32,7 @@
 
 # setup
 #
-export VERSION="3.4.0 2025-03-16"
+export VERSION="3.5.0 2025-05-20"
 PYTHON3_PROG=$(type -P python3)
 export PYTHON3_PROG
 SHA256SUM_PROG=$(type -P sha256sum)
@@ -60,10 +60,10 @@ export USAGE="usage: $0 [-n] [-v] [-f] [-i] [-t] [-s] [-S] [-C] [-d] [-p khc_pat
     -n		Do nothing (def: do)
     -v		Verbose mode (def: quiet)
 
-    -f		Force cleanup if missing: authorized_keys config id_rsa id_rsa.pub known_hosts
-		    NOTE: if id_rsa.LOCKED exists, OK if id_rsa is missing
-		    NOTE: if id_rsa.pub.LOCKED exists, OK if id_rsa.pub is missing
-    -i		Do not warn if missing:   authorized_keys config id_rsa id_rsa.pub known_hosts
+    -f		Force cleanup if missing: authorized_keys config id_ed25519 id_ed25519.pub known_hosts
+		    NOTE: if id_ed25519.LOCKED exists, OK if id_ed25519 is missing
+		    NOTE: if id_ed25519.pub.LOCKED exists, OK if id_ed25519.pub is missing
+    -i		Do not warn if missing:   authorized_keys config id_ed25519 id_ed25519.pub known_hosts
 		    NOTE: -i implies -f
     -t		Touch to form empty authorized_keys config known_hosts if missing (def: do not touch)
 		    NOTE: if authorized_keys.LOCKED exists, authorized_keys is not touched
@@ -235,23 +235,23 @@ if [[ -z $F_FLAG && -z $T_FLAG && -s authorized_keys && -f authorized_keys.LOCKE
     echo "$0: FATAL: exit 8" 1>&2
     exit 8
 fi
-if [[ -z $F_FLAG && ! -f id_rsa && ! -f id_rsa.LOCKED ]]; then
-    echo "$0: FATAL: $dir is missing id_rsa" 1>&2
+if [[ -z $F_FLAG && ! -f id_ed25519 && ! -f id_ed25519.LOCKED ]]; then
+    echo "$0: FATAL: $dir is missing id_ed25519" 1>&2
     echo "$0: FATAL: exit 9" 1>&2
     exit 9
 fi
-if [[ -z $F_FLAG && -f id_rsa && -f id_rsa.LOCKED ]]; then
-    echo "$0: FATAL: $dir has both id_rsa and id_rsa.LOCKED" 1>&2
+if [[ -z $F_FLAG && -f id_ed25519 && -f id_ed25519.LOCKED ]]; then
+    echo "$0: FATAL: $dir has both id_ed25519 and id_ed25519.LOCKED" 1>&2
     echo "$0: FATAL: exit 10" 1>&2
     exit 10
 fi
-if [[ -z $F_FLAG && ! -f id_rsa.pub && ! -f id_rsa.pub.LOCKED ]]; then
-    echo "$0: FATAL: $dir is missing id_rsa.pub" 1>&2
+if [[ -z $F_FLAG && ! -f id_ed25519.pub && ! -f id_ed25519.pub.LOCKED ]]; then
+    echo "$0: FATAL: $dir is missing id_ed25519.pub" 1>&2
     echo "$0: FATAL: exit 11" 1>&2
     exit 11
 fi
-if [[ -z $F_FLAG && -f id_rsa.pub && -f id_rsa.pub.LOCKED ]]; then
-    echo "$0: FATAL: $dir has both id_rsa.pub and id_rsa.pub.LOCKED" 1>&2
+if [[ -z $F_FLAG && -f id_ed25519.pub && -f id_ed25519.pub.LOCKED ]]; then
+    echo "$0: FATAL: $dir has both id_ed25519.pub and id_ed25519.pub.LOCKED" 1>&2
     echo "$0: FATAL: exit 12" 1>&2
     exit 12
 fi
@@ -832,17 +832,17 @@ if [[ -z $N_FLAG ]]; then
 	    xargs -r -0 chmod 0400
     fi
     if [[ -n $V_FLAG ]]; then
-	find . -mindepth 1 -maxdepth 1 -type f ! -name 'id_rsa.pub*' -name 'id_rsa*' -print0 |
+	find . -mindepth 1 -maxdepth 1 -type f ! -name 'id_*.pub*' -name 'id_*' -print0 |
 	    xargs -r -t -0 chmod -v 0400
     else
-	find . -mindepth 1 -maxdepth 1 -type f ! -name 'id_rsa.pub*' -name 'id_rsa*' -print0 |
+	find . -mindepth 1 -maxdepth 1 -type f ! -name 'id_*.pub*' -name 'id_*' -print0 |
 	    xargs -r -0 chmod 0400
     fi
     if [[ -n $V_FLAG ]]; then
-	find . -mindepth 1 -maxdepth 1 -type f -name 'id_rsa.pub*' -print0 |
+	find . -mindepth 1 -maxdepth 1 -type f -name 'id_*.pub*' -print0 |
 	    xargs -r -t -0 chmod -v 0444
     else
-	find . -mindepth 1 -maxdepth 1 -type f -name 'id_rsa.pub*' -print0 |
+	find . -mindepth 1 -maxdepth 1 -type f -name 'id_*.pub*' -print0 |
 	    xargs -r -0 chmod 0444
     fi
     if [[ -n $V_FLAG ]]; then
@@ -858,9 +858,9 @@ elif [[ -n $V_FLAG ]]; then
 	xargs -r -0 echo "chmod -v 0400"
     find . -mindepth 1 -maxdepth 1 -type f -name 'config*' -print0 |
 	xargs -r -0 echo "chmod -v 0400"
-    find . -mindepth 1 -maxdepth 1 -type f ! -name 'id_rsa.pub*' -name 'id_rsa*' -print0 |
+    find . -mindepth 1 -maxdepth 1 -type f ! -name 'id_*.pub*' -name 'id_*' -print0 |
 	xargs -r -0 echo "chmod -v 0400"
-    find . -mindepth 1 -maxdepth 1 -type f -name 'id_rsa.pub*' -print0 |
+    find . -mindepth 1 -maxdepth 1 -type f -name 'id_*.pub*' -print0 |
 	xargs -r -0 echo "chmod -v 0444"
     find . -mindepth 1 -maxdepth 1 -type f -name 'known_hosts*' -print0 |
 	xargs -r -0 echo "chmod -v 0600"
@@ -896,17 +896,17 @@ if [[ -n $USER_GROUP ]]; then
 		xargs -r -0 chown "$USER_GROUP"
 	fi
 	if [[ -n $V_FLAG ]]; then
-	    find . -mindepth 1 -maxdepth 1 -type f ! -name 'id_rsa.pub*' -name 'id_rsa*' -print0 |
+	    find . -mindepth 1 -maxdepth 1 -type f ! -name 'id_*.pub*' -name 'id_*' -print0 |
 		xargs -r -t -0 chown -v "$USER_GROUP"
 	else
-	    find . -mindepth 1 -maxdepth 1 -type f ! -name 'id_rsa.pub*' -name 'id_rsa*' -print0 |
+	    find . -mindepth 1 -maxdepth 1 -type f ! -name 'id_*.pub*' -name 'id_*' -print0 |
 		xargs -r -0 chown "$USER_GROUP"
 	fi
 	if [[ -n $V_FLAG ]]; then
-	    find . -mindepth 1 -maxdepth 1 -type f -name 'id_rsa.pub*' -print0 |
+	    find . -mindepth 1 -maxdepth 1 -type f -name 'id_*.pub*' -print0 |
 		xargs -r -t -0 chown -v "$USER_GROUP"
 	else
-	    find . -mindepth 1 -maxdepth 1 -type f -name 'id_rsa.pub*' -print0 |
+	    find . -mindepth 1 -maxdepth 1 -type f -name 'id_*.pub*' -print0 |
 		xargs -r -0 chown "$USER_GROUP"
 	fi
 	if [[ -n $V_FLAG ]]; then
@@ -922,9 +922,9 @@ if [[ -n $USER_GROUP ]]; then
 	    xargs -r -0 echo "chown -v $USER_GROUP"
 	find . -mindepth 1 -maxdepth 1 -type f -name 'config*' -print0 |
 	    xargs -r -0 echo "chown -v $USER_GROUP"
-	find . -mindepth 1 -maxdepth 1 -type f ! -name 'id_rsa.pub*' -name 'id_rsa*' -print0 |
+	find . -mindepth 1 -maxdepth 1 -type f ! -name 'id_*.pub*' -name 'id_*' -print0 |
 	    xargs -r -0 echo "chown -v $USER_GROUP"
-	find . -mindepth 1 -maxdepth 1 -type f -name 'id_rsa.pub*' -print0 |
+	find . -mindepth 1 -maxdepth 1 -type f -name 'id_*.pub*' -print0 |
 	    xargs -r -0 echo "chown -v $USER_GROUP"
 	find . -mindepth 1 -maxdepth 1 -type f -name 'known_hosts*' -print0 |
 	    xargs -r -0 echo "chown -v $USER_GROUP"
@@ -939,7 +939,7 @@ fi
 if [[ -n $V_FLAG ]]; then
     echo '# Insure that critical files have a dated copy'
 fi
-for file in authorized_keys config id_rsa id_rsa.pub known_hosts; do
+for file in authorized_keys config id_ed25519 id_ed25519.pub known_hosts; do
 
     # deal with the case where we have authorized_keys.LOCKED
     #
@@ -950,21 +950,21 @@ for file in authorized_keys config id_rsa id_rsa.pub known_hosts; do
     if [[ $file == "authorized_keys" && -f authorized_keys.LOCKED ]]; then
         src="authorized_keys.LOCKED"
 
-    # deal with the case where we have id_rsa
+    # deal with the case where we have id_ed25519
     #
-    # When we have id_rsa.LOCKED we need to form a dated file
-    # as if we have id_rsa while using the contents of id_rsa.LOCKED
+    # When we have id_ed25519.LOCKED we need to form a dated file
+    # as if we have id_ed25519 while using the contents of id_ed25519.LOCKED
     #
-    elif [[ $file == "id_rsa" && -f id_rsa.LOCKED ]]; then
-        src="id_rsa.LOCKED"
+    elif [[ $file == "id_ed25519" && -f id_ed25519.LOCKED ]]; then
+        src="id_ed25519.LOCKED"
 
-    # deal with the case where we have id_rsa.pub
+    # deal with the case where we have id_ed25519.pub
     #
-    # When we have id_rsa.pub.LOCKED we need to form a dated file
-    # as if we have id_rsa.pub while using the contents of id_rsa.pub.LOCKED
+    # When we have id_ed25519.pub.LOCKED we need to form a dated file
+    # as if we have id_ed25519.pub while using the contents of id_ed25519.pub.LOCKED
     #
-    elif [[ $file == "id_rsa.pub" && -f id_rsa.pub.LOCKED ]]; then
-        src="id_rsa.pub.LOCKED"
+    elif [[ $file == "id_ed25519.pub" && -f id_ed25519.pub.LOCKED ]]; then
+        src="id_ed25519.pub.LOCKED"
     fi
 
     # catch the case of a missing critical file
@@ -1040,7 +1040,7 @@ fi
 if [[ -n $V_FLAG ]]; then
     echo '# Processing fileset moves'
 fi
-for file in authorized_keys config id_rsa id_rsa.pub known_hosts; do
+for file in authorized_keys config id_ed25519 id_ed25519.pub id_rsa id_rsa.pub known_hosts; do
 
     # deal with the case where we have authorized_keys.LOCKED
     #
@@ -1051,21 +1051,37 @@ for file in authorized_keys config id_rsa id_rsa.pub known_hosts; do
     if [[ $file == "authorized_keys" && -f authorized_keys.LOCKED ]]; then
         src="authorized_keys.LOCKED"
 
+    # deal with the case where we have id_ed25519
+    #
+    # When we have id_ed25519.LOCKED we need to form a dated file
+    # as if we have id_ed25519 while using the contents of id_ed25519.LOCKED
+    #
+    elif [[ $file == "id_ed25519" && -f id_ed25519.LOCKED ]]; then
+	src="id_ed25519.LOCKED"
+
+    # deal with the case where we have id_ed25519.pub
+    #
+    # When we have id_ed25519.pub.LOCKED we need to form a dated file
+    # as if we have id_ed25519.pub while using the contents of id_ed25519.pub.LOCKED
+    #
+    elif [[ $file == "id_ed25519.pub" && -f id_ed25519.pub.LOCKED ]]; then
+	src="id_ed25519.pub.LOCKED"
+
     # deal with the case where we have id_rsa
     #
     # When we have id_rsa.LOCKED we need to form a dated file
     # as if we have id_rsa while using the contents of id_rsa.LOCKED
     #
-elif [[ $file == "id_rsa" && -f id_rsa.LOCKED ]]; then
-    src="id_rsa.LOCKED"
+    elif [[ $file == "id_rsa" && -f id_rsa.LOCKED ]]; then
+	src="id_rsa.LOCKED"
 
     # deal with the case where we have id_rsa.pub
     #
     # When we have id_rsa.pub.LOCKED we need to form a dated file
     # as if we have id_rsa.pub while using the contents of id_rsa.pub.LOCKED
     #
-elif [[ $file == "id_rsa.pub" && -f id_rsa.pub.LOCKED ]]; then
-    src="id_rsa.pub.LOCKED"
+    elif [[ $file == "id_rsa.pub" && -f id_rsa.pub.LOCKED ]]; then
+	src="id_rsa.pub.LOCKED"
     fi
 
     if [[ ! -f $src && -n $I_FLAG ]]; then
