Added -p and -P, improved -v, version 3.2.6
Added -p known_hosts_cleanup_path.

Added -P python3_path

Improved -v output.

Version: 3.2.6

diff --git a/cleanupssh b/cleanupssh
--- a/cleanupssh
+++ b/cleanupssh
@@ -28,7 +28,7 @@
 
 # parse args
 #
-export VERSION="3.2.5"
+export VERSION="3.2.6"
 export USAGE="usage: $0 [-n] [-v] [-f] [-i] [-t] [-s] [-S] [-c user[:group]] [-V] [-h] dir
 
     -n		Do nothing (def: do)
@@ -40,6 +40,9 @@ export USAGE="usage: $0 [-n] [-v] [-f] [-i] [-t] [-s] [-S] [-c user[:group]] [-V
     -t		Touch to form empty authorized_keys config known_hosts if missing (def: do not touch)
     -s		Do not unique sort and cleanup authorized_keys (def: do)
     -S		Do not unique sort and cleanup known_hosts (def: do with known_hosts_cleanup)
+
+    -p khc_path	Absolute path to known_hosts_cleanup (def: search for known_hosts_cleanup)
+    -P python3	Absolute path to python3 (def: search for python3)
 
     -c user[:group]	Chown critical files as user:group (def: do not chown)
 			    NOTE: Ignored if UID != 0 (i.e., not root)
@@ -59,7 +62,9 @@ export T_FLAG=
 export S_FLAG=
 export CAP_S_FLAG=
 export USER_GROUP=
-while getopts hnvfitsSc:V flag; do
+export KNOWN_HOSTS_CLEANUP=
+export PYTHON3=
+while getopts hnvfitsSp:P:c:V flag; do
     case "$flag" in
     h) echo "$USAGE" 1>&2; exit 0 ;;
     n) N_FLAG="-n" ;;
@@ -69,6 +74,8 @@ while getopts hnvfitsSc:V flag; do
     t) T_FLAG="-t" ;;
     s) S_FLAG="-s" ;;
     S) CAP_S_FLAG="-S" ;;
+    p) KNOWN_HOSTS_CLEANUP="$OPTARG" ;;
+    P) PYTHON3="$OPTARG" ;;
     c) USER_GROUP="$OPTARG" ;;
     V) echo "$0: Version: $VERSION" ; exit 0 ;;
     ?) echo "$0: FATAL: unknown or invalid -flag" 1>&2 ;
@@ -96,6 +103,15 @@ if [[ -n $USER_GROUP ]]; then
 	    echo "$0: Warning: because UID: $UID != 0, ignoring: -c $USER_GROUP" 1>&2
 	fi
 	USER_GROUP=
+    fi
+fi
+if [[ -n "$V_FLAG" ]]; then
+    echo "# cleanupssh version: $VERSION"
+    if [[ -n "$KNOWN_HOSTS_CLEANUP" ]]; then
+	echo "# -p set known_hosts_cleanup path to: $KNOWN_HOSTS_CLEANUP"
+    fi
+    if [[ -n "$PYTHON3" ]]; then
+	echo "# -P set python3 path to: $PYTHON3"
     fi
 fi
 
@@ -157,25 +173,31 @@ fi
 
 # look for known_hosts_cleanup tool
 #
-export KNOWN_HOSTS_CLEANUP
 if [[ -z $CAP_S_FLAG ]]; then
-    KNOWN_HOSTS_CLEANUP=$(which known_hosts_cleanup 2>/dev/null)
-    status="$?"
-    if [[ $status -ne 0 || ! -x "$KNOWN_HOSTS_CLEANUP" ]]; then
-	# try the installed location of known_hosts_cleanup
-	KNOWN_HOSTS_CLEANUP="/usr/global/sbin/known_hosts_cleanup"
+    if [[ -z "$KNOWN_HOSTS_CLEANUP" ]]; then
+	KNOWN_HOSTS_CLEANUP=$(which known_hosts_cleanup 2>/dev/null)
+	status="$?"
+	if [[ $status -ne 0 || ! -x "$KNOWN_HOSTS_CLEANUP" ]]; then
+	    # try the installed location of known_hosts_cleanup
+	    KNOWN_HOSTS_CLEANUP="/usr/global/sbin/known_hosts_cleanup"
+	fi
     fi
     if [[ ! -x "$KNOWN_HOSTS_CLEANUP" ]]; then
 	# try the other installed location of known_hosts_cleanup
 	KNOWN_HOSTS_CLEANUP="$HOME/dot/tool/known_hosts_cleanup"
 	if [[ ! -x "$KNOWN_HOSTS_CLEANUP" ]]; then
-	    # no known_hosts_cleanup is available
-	    KNOWN_HOSTS_CLEANUP=
-	    echo "$0: Warning: cannot find known_hosts_cleanup, will just sort known_hosts" 1>&2
+	    KNOWN_HOSTS_CLEANUP="$HOME/bin/known_hosts_cleanup"
+	    if [[ ! -x "$KNOWN_HOSTS_CLEANUP" ]]; then
+		# no known_hosts_cleanup is available
+		KNOWN_HOSTS_CLEANUP=
+		echo "$0: Warning: cannot find known_hosts_cleanup, will just sort known_hosts" 1>&2
+		CAP_S_FLAG='-S'
+		echo "$0: Warning: forcing -S to disable known_hosts_cleanup" 1>&2
+	    fi
 	else
 	    if [[ -n "$V_FLAG" ]]; then
 		echo
-		echo "# will use known_hosts_cleanup also from: $KNOWN_HOSTS_CLEANUP"
+		echo "# will use alternate known_hosts_cleanup from: $KNOWN_HOSTS_CLEANUP"
 	    fi
 	fi
     else
@@ -191,19 +213,21 @@ fi
 
 # look for python3
 #
-export PYTHON3 PYTHON3_VERSION
-if [[ -x /usr/bin/python3 ]]; then
-    PYTHON3="/usr/bin/python3"
-elif [[ -x /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 ]]; then
-    PYTHON3="/Library/Frameworks/Python.framework/Versions/3.7/bin/python3"
-elif [[ -x /bin/python3 ]]; then
-    PYTHON3="/bin/python3"
-elif [[ -x /usr/local/bin/python3 ]]; then
-    PYTHON3="/usr/local/bin/python3"
-elif [[ -x /usr/global/bin/python3 ]]; then
-    PYTHON3="/usr/global/bin/python3"
-else
-    PYTHON3=$(which python3 2>/dev/null)
+export PYTHON3_VERSION
+if [[ -z "$PYTHON3" || ! -x "$PYTHON3" ]]; then
+    if [[ -x /usr/bin/python3 ]]; then
+	PYTHON3="/usr/bin/python3"
+    elif [[ -x /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 ]]; then
+	PYTHON3="/Library/Frameworks/Python.framework/Versions/3.7/bin/python3"
+    elif [[ -x /bin/python3 ]]; then
+	PYTHON3="/bin/python3"
+    elif [[ -x /usr/local/bin/python3 ]]; then
+	PYTHON3="/usr/local/bin/python3"
+    elif [[ -x /usr/global/bin/python3 ]]; then
+	PYTHON3="/usr/global/bin/python3"
+    else
+	PYTHON3=$(which python3 2>/dev/null)
+    fi
 fi
 if [[ -z $PYTHON3 ]]; then
     echo "$0: Warning: cannot find python3 executable" 1>&2
@@ -552,6 +576,7 @@ if [[ -z $CAP_S_FLAG ]]; then
     else
 	if [[ -n "$V_FLAG" ]]; then
 	    echo "$PYTHON3 $KNOWN_HOSTS_CLEANUP -v known_hosts > $SORTED_TMP"
+	    echo
 	fi
 	if [[ -z "$N_FLAG" ]]; then
 	    if [[ -n "$V_FLAG" ]]; then
